"""Convert the JSON lines produced by tools/extract_dialect_tests.py into MoonBit
conformance fixtures: src/dialect_tests/fixture_<module>_test.mbt.

Each fixture is a flat Array[String] of 5-tuples: read, write, flags, sql, expected.
Flags: p = pretty, i = identify, u = generation must raise UnsupportedError,
I = unsupported_level Ignore (validate_all) instead of Warn.

Usage: python3 tools/gen_dialect_fixtures.py cases.jsonl
"""

import collections
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src", "dialect_tests")


def mbt_str(s):
    out = ['"']
    for ch in s:
        o = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif o < 0x20 or o == 0x7F or 0xD800 <= o <= 0xDFFF:
            out.append("\\u{%x}" % o)
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def main(path):
    by_module = collections.OrderedDict()
    seen = set()
    for line in open(path):
        c = json.loads(line)
        if "error" in c:
            continue
        module = c["test"].split(".")[2].removeprefix("test_")
        flags = ""
        if c.get("pretty"):
            flags += "p"
        if c.get("identify"):
            flags += "i"
        if c.get("unsupported"):
            flags += "u"
        if c["kind"] in ("all_read", "all_write"):
            flags += "I"
        row = (c["read"], c["write"], flags, c["sql"], c.get("out", ""))
        if row in seen:
            continue
        seen.add(row)
        by_module.setdefault(module, []).append(row)

    os.makedirs(OUT, exist_ok=True)
    for f in os.listdir(OUT):
        if f.startswith("fixture_"):
            os.remove(os.path.join(OUT, f))
    tests = []
    for module, rows in by_module.items():
        lines = [
            "// Code generated by tools/gen_dialect_fixtures.py. DO NOT EDIT.",
            "",
            "///|",
            f"let {module}_cases : Array[String] = [",
        ]
        for row in rows:
            lines.append("  " + ", ".join(mbt_str(x) for x in row) + ",")
        lines.append("]")
        with open(os.path.join(OUT, f"fixture_{module}_test.mbt"), "w") as f:
            f.write("\n".join(lines) + "\n")
        tests.append(
            f'///|\ntest "dialect {module}" {{\n  run_dialect_cases("{module}", {module}_cases)\n}}\n'
        )
    with open(os.path.join(OUT, "dialect_cases_test.mbt"), "w") as f:
        f.write("// Code generated by tools/gen_dialect_fixtures.py. DO NOT EDIT.\n\n" + "\n".join(tests))
    sys.stderr.write(f"{sum(len(r) for r in by_module.values())} cases in {len(by_module)} modules\n")


if __name__ == "__main__":
    main(sys.argv[1])
