"""Generate src/core/gen_kind_modules.mbt: the Python module of every expression class.

Used for Python-style class paths in error messages, e.g.
"<class 'sqlglot.expressions.core.Aliases'>". Same class order as tools/gen_meta.py.
Set SQLGLOT_REPO to the Python sqlglot checkout (default <root>/.repos/sqlglot).
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SG = os.environ.get("SQLGLOT_REPO", os.path.join(ROOT, ".repos", "sqlglot"))
sys.path.insert(0, SG)

import gen_meta  # noqa: E402
from gen_meta import mbt_str  # noqa: E402


def main():
    classes = gen_meta.all_classes()
    classes.sort(key=lambda c: c.__name__)
    lines = ["// Code generated by tools/gen_kind_modules.py. DO NOT EDIT.", ""]
    lines.append("///|")
    lines.append("/// Python module of each expression class (indexed by `Kind::id`).")
    lines.append("let kind_modules : FixedArray[String] = [")
    for c in classes:
        lines.append(f"  {mbt_str(c.__module__)},")
    lines.append("]")
    out = os.path.join(ROOT, "src", "core", "gen_kind_modules.mbt")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
