"""Generate fixtures for deep unary/parenthesis chains into src/robust_tests.

    python tools/gen_deep_fixtures.py

The port generates long chains of NOT / unary minus / ~ / parentheses iteratively (see
`Generator::unary_chain_sql`); these fixtures pin its output to Python's (recursive)
generator. A chain is described outermost first by a spec string: `-` Neg, `N` Not, `~`
BitwiseNot, `(` Paren, and `c` marks that the following link carries the comment `c<i>`
(`i`: the link's position, outermost 0). The innermost operand is the column `x`.

Writes src/robust_tests/fixture_deep_test.mbt.
"""

import os
import random
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SG = os.path.join(ROOT, ".repos", "sqlglot")
if not os.path.isdir(SG):
    SG = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(ROOT))), ".repos", "sqlglot")
sys.path.insert(0, SG)
sys.setrecursionlimit(20000)

from sqlglot import exp  # noqa: E402

OUT = os.path.join(ROOT, "src", "robust_tests", "fixture_deep_test.mbt")

KINDS = {"-": exp.Neg, "N": exp.Not, "~": exp.BitwiseNot, "(": exp.Paren}


def build(spec):
    links = []
    comment = False
    for ch in spec:
        if ch == "c":
            comment = True
            continue
        links.append((KINDS[ch], comment))
        comment = False
    e = exp.column("x")
    for i in reversed(range(len(links))):
        klass, has_comment = links[i]
        e = klass(this=e)
        if has_comment:
            e.add_comments([f"c{i}"])
    return e


def mbt_str(s):
    out = ['"']
    for ch in s:
        o = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif o < 0x20 or o >= 0x7F:
            out.append("\\u{%x}" % o)
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def main():
    rnd = random.Random(7)
    specs = ["-" * 100, "N" * 100, "~" * 100, "(" * 100, "-(" * 60, "-~-" * 40]
    for _ in range(12):
        n = rnd.randint(64, 160)
        spec = []
        for _ in range(n):
            if rnd.random() < 0.05:
                spec.append("c")
            spec.append(rnd.choice("-N~("))
        specs.append("".join(spec))
    rows = []
    for spec in specs:
        e = build(spec)
        for pretty in (False, True):
            rows.append((spec, pretty, e.sql(pretty=pretty)))
    lines = [
        "// Code generated by tools/gen_deep_fixtures.py. DO NOT EDIT.\n",
        "///|\n/// (chain spec, pretty, Python's SQL)\nlet deep_chains : Array[(String, Bool, String)] = [",
    ]
    for spec, pretty, sql in rows:
        lines.append(f"  ({mbt_str(spec)}, {'true' if pretty else 'false'}, {mbt_str(sql)}),")
    lines.append("]\n")
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
