"""Convert the JSON lines produced by tools/extract_dialect_tests.py into MoonBit
conformance fixtures: src/dialect_tests/fixture_<module>_test.mbt.

Each `<module>_cases` fixture is a flat Array[String] of 5-tuples: read, write, flags,
sql, expected. Flags: p = pretty, i = identify, u = generation must raise
UnsupportedError, I = unsupported_level Ignore (validate_all) instead of Warn,
c = parsing must log the "contains unsupported syntax" (Command fallback) warning,
E = the case must raise; `expected` is then "<ErrorClass>: <message>".

Each `<module>_error_cases` fixture is a flat Array[String] of 6-tuples for the
`parse_one` / `parse` / `transpile` / `Expr.sql` calls made directly by the Python tests
that raised a sqlglot error: fn, dialect, options (JSON object), input (SQL, or the
`serde.dump` JSON of the expression for `sql`), error class, message.

With a manifest (written by `extract_dialect_tests.py --manifest`), also writes
docs/dialect-test-manifest.md: for every Python test method, how many of its checks are
replayed from fixtures and whether its direct assertions are hand-ported in
src/dialect_unit_tests (a `test "TestClass.test_method"` block in test_<module>_test.mbt)
or deliberately excluded (EXCLUDED below). Exits with status 1 if a test method with
direct assertions is neither ported nor excluded.

Usage: python3 tools/gen_dialect_fixtures.py cases.jsonl [manifest.json]
"""

import ast
import collections
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src", "dialect_tests")
UNIT = os.path.join(ROOT, "src", "dialect_unit_tests")
PY_TESTS = os.path.join(ROOT, ".repos", "sqlglot", "tests", "dialects")
MANIFEST = os.path.join(ROOT, "docs", "dialect-test-manifest.md")

# Test methods whose direct assertions are intentionally not ported, with the reason.
EXCLUDED = {
    "TestDialect.test_lazy_load": "checks Python's lazy module import machinery",
}


def mbt_str(s):
    out = ['"']
    for ch in s:
        o = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif o < 0x20 or o == 0x7F or 0xD800 <= o <= 0xDFFF:
            out.append("\\u{%x}" % o)
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def module_of(test_id):
    return test_id.split(".")[2].removeprefix("test_")


def case_row(c):
    flags = ""
    if c.get("pretty"):
        flags += "p"
    if c.get("identify"):
        flags += "i"
    if c.get("unsupported"):
        flags += "u"
    if c["kind"] in ("all_read", "all_write"):
        flags += "I"
    if c.get("command"):
        flags += "c"
    if "error" in c:
        flags += "E"
        expected = f"{c['error']}: {c['message']}"
    else:
        expected = c.get("out", "")
    return (c["read"], c["write"], flags, c["sql"], expected)


def error_row(c):
    if c["fn"] == "sql":
        source = json.dumps(c["tree"], ensure_ascii=False, separators=(",", ":"))
    else:
        source = c["sql"]
    opts = json.dumps(c["opts"], sort_keys=True, separators=(",", ":"))
    return (c["fn"], c["dialect"], opts, source, c["error"], c["message"])


def write_fixtures(path):
    by_module = collections.OrderedDict()
    errors_by_module = collections.OrderedDict()
    seen = set()
    for line in open(path):
        c = json.loads(line)
        module = module_of(c["test"])
        if c["kind"] == "error_call":
            row, target = error_row(c), errors_by_module
        else:
            row, target = case_row(c), by_module
        if row in seen:
            continue
        seen.add(row)
        target.setdefault(module, []).append(row)

    os.makedirs(OUT, exist_ok=True)
    for f in os.listdir(OUT):
        if f.startswith("fixture_"):
            os.remove(os.path.join(OUT, f))
    tests = []
    for module in sorted(set(by_module) | set(errors_by_module)):
        lines = ["// Code generated by tools/gen_dialect_fixtures.py. DO NOT EDIT.", ""]
        if module in by_module:
            lines += ["///|", f"let {module}_cases : Array[String] = ["]
            for row in by_module[module]:
                lines.append("  " + ", ".join(mbt_str(x) for x in row) + ",")
            lines.append("]")
            tests.append(
                f'///|\ntest "dialect {module}" {{\n  run_dialect_cases("{module}", {module}_cases)\n}}\n'
            )
        if module in errors_by_module:
            if module in by_module:
                lines.append("")
            lines += ["///|", f"let {module}_error_cases : Array[String] = ["]
            for row in errors_by_module[module]:
                lines.append("  " + ", ".join(mbt_str(x) for x in row) + ",")
            lines.append("]")
            tests.append(
                f'///|\ntest "dialect errors {module}" {{\n'
                f'  run_error_cases("{module}", {module}_error_cases)\n}}\n'
            )
        with open(os.path.join(OUT, f"fixture_{module}_test.mbt"), "w") as f:
            f.write("\n".join(lines) + "\n")
    with open(os.path.join(OUT, "dialect_cases_test.mbt"), "w") as f:
        f.write("// Code generated by tools/gen_dialect_fixtures.py. DO NOT EDIT.\n\n" + "\n".join(tests))
    sys.stderr.write(
        f"{sum(len(r) for r in by_module.values())} cases and "
        f"{sum(len(r) for r in errors_by_module.values())} error cases in "
        f"{len(set(by_module) | set(errors_by_module))} modules\n"
    )


def ported_tests():
    """`TestClass.test_method` names of the hand-ported tests, per module."""
    ported = collections.defaultdict(set)
    if not os.path.isdir(UNIT):
        return ported
    for f in os.listdir(UNIT):
        m = re.fullmatch(r"test_(\w+)_test\.mbt", f)
        if not m:
            continue
        for name in re.findall(r'^test "(Test\w+\.test_\w+)', open(os.path.join(UNIT, f)).read(), re.M):
            ported[m.group(1)].add(name)
    return ported


def bare_asserts():
    """Number of plain `assert` statements per `module:TestClass.test_method` (these
    can't be counted at run time like the `self.assert*` calls)."""
    counts = collections.Counter()
    for f in os.listdir(PY_TESTS):
        if not (f.startswith("test_") and f.endswith(".py")):
            continue
        module = f[len("test_"):-len(".py")]
        tree = ast.parse(open(os.path.join(PY_TESTS, f)).read())
        for cls in tree.body:
            if not isinstance(cls, ast.ClassDef):
                continue
            for fn in cls.body:
                if isinstance(fn, ast.FunctionDef) and fn.name.startswith("test_"):
                    n = sum(isinstance(node, ast.Assert) for node in ast.walk(fn))
                    if n:
                        counts[f"{module}:{cls.name}.{fn.name}"] = n
    return counts


def write_manifest(path):
    stats = json.load(open(path))
    ported = ported_tests()
    bare = bare_asserts()
    rows = []
    missing = []
    totals = collections.Counter()
    for test_id, s in sorted(stats.items()):
        if not test_id.startswith("tests.dialects."):
            continue
        module = module_of(test_id)
        short = ".".join(test_id.split(".")[3:])
        replayed = sum(s.get(k, 0) for k in ("identity", "transpile", "all_read", "all_write", "error_call"))
        direct = s.get("direct_asserts", 0) + bare.get(f"{module}:{short}", 0)
        if short in ported.get(module, ()):
            status = "ported"
        elif short in EXCLUDED:
            status = "excluded: " + EXCLUDED[short]
        elif direct:
            status = "MISSING"
            missing.append(test_id)
        else:
            status = "fixtures only"
        totals["methods"] += 1
        totals["replayed"] += replayed
        totals["direct"] += direct
        totals[status.split(":")[0]] += 1
        unrecorded = s.get("unrecorded_errors", 0)
        rows.append(f"| {module} | {short} | {replayed} | {direct} | {unrecorded} | {status} |")
    for module, names in sorted(ported.items()):
        known = {".".join(t.split(".")[3:]) for t in stats if module_of(t) == module}
        for n in sorted(names - known):
            sys.stderr.write(f"warning: ported test {module}:{n} matches no Python test method\n")
    header = [
        "# Dialect test coverage manifest",
        "",
        "Generated by tools/gen_dialect_fixtures.py from the run of tools/extract_dialect_tests.py",
        "over `tests/dialects/test_*.py`. DO NOT EDIT.",
        "",
        "- *replayed*: Validator checks (validate_identity / validate_all / validate_transpile)",
        "  and failing direct API calls (error cases) replayed by src/dialect_tests.",
        "- *direct*: assertions the method makes outside the Validator helpers (`self.assert*`",
        "  calls counted at run time, so loops count every iteration, plus plain `assert`",
        "  statements counted statically); these are hand-ported in",
        "  src/dialect_unit_tests/test_<module>_test.mbt (*ported*).",
        "- *unrecorded errors*: failing calls whose arguments couldn't be recorded as data.",
        "",
        f"Methods: {totals['methods']}, replayed checks: {totals['replayed']}, "
        f"direct assertions: {totals['direct']}; ported: {totals['ported']}, "
        f"fixtures only: {totals['fixtures only']}, excluded: {totals['excluded']}, "
        f"missing: {totals['MISSING']}.",
        "",
        "| module | test method | replayed | direct | unrecorded errors | status |",
        "|---|---|---|---|---|---|",
    ]
    os.makedirs(os.path.dirname(MANIFEST), exist_ok=True)
    with open(MANIFEST, "w") as f:
        f.write("\n".join(header + rows) + "\n")
    if missing:
        sys.stderr.write(f"{len(missing)} test methods with direct assertions are not ported:\n")
        for m in missing:
            sys.stderr.write(f"  {m}\n")
        return False
    return True


if __name__ == "__main__":
    write_fixtures(sys.argv[1])
    if len(sys.argv) > 2 and not write_manifest(sys.argv[2]):
        sys.exit(1)
