"""Generate MoonBit diff fixtures by recording the diff() calls of tests/test_diff.py.

Calls whose inputs round-trip through SQL (no pre-matchings) are replayed by the MoonBit
test; edits are compared as sorted lists of `Kind(class: sql -> sql)` strings, since the
Python edit script order depends on set iteration order.

    python tools/gen_diff_fixtures.py
"""

import json
import os
import sys
import unittest
import warnings

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SG = os.path.join(ROOT, ".repos", "sqlglot")
sys.path.insert(0, SG)
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
warnings.filterwarnings("ignore")

import logging  # noqa: E402

logging.getLogger("sqlglot").setLevel(logging.CRITICAL)

from gen_meta import mbt_str  # noqa: E402

import sqlglot  # noqa: E402
import importlib  # noqa: E402

diff_mod = importlib.import_module("sqlglot.diff")
from sqlglot import exp, parse_one  # noqa: E402

OUT = os.path.join(ROOT, "src", "diff_tests")

real_diff = diff_mod.diff
recorded = []


def edit_str(e):
    def s(x):
        return f"{type(x).__name__}: {x.sql()}"

    if isinstance(e, (diff_mod.Insert, diff_mod.Remove)):
        return f"{type(e).__name__}({s(e.expression)})"
    return f"{type(e).__name__}({s(e.source)} -> {e.target.sql()})"


def recording_diff(source, target, matchings=None, delta_only=False, **kwargs):
    src_sql = source.sql()
    tgt_sql = target.sql()
    result = real_diff(source, target, matchings=matchings, delta_only=delta_only, **kwargs)
    roundtrips = (
        parse_one(src_sql) == source and parse_one(tgt_sql) == target and not kwargs
    )
    if not matchings and roundtrips:
        key = json.dumps({"source": src_sql, "target": tgt_sql, "delta_only": delta_only})
        recorded.append((key, "\n".join(sorted(edit_str(e) for e in result))))
    return result


def main():
    diff_mod.diff = recording_diff
    import tests.test_diff as td

    td.diff = recording_diff
    suite = unittest.defaultTestLoader.loadTestsFromModule(td)
    unittest.TextTestRunner(stream=open(os.devnull, "w")).run(suite)

    os.makedirs(OUT, exist_ok=True)
    seen = set()
    with open(os.path.join(OUT, "fixture_diff_test.mbt"), "w") as f:
        f.write("// Code generated by tools/gen_diff_fixtures.py. DO NOT EDIT.\n\n")
        f.write("///|\nlet diff_fixtures : Array[String] = [\n")
        n = 0
        for key, out in recorded:
            if key in seen:
                continue
            seen.add(key)
            n += 1
            f.write(f"  {mbt_str(key)},\n  {mbt_str(out)},\n")
        f.write("]\n")
    print("diff calls:", n)


if __name__ == "__main__":
    main()
