"""Generate MoonBit planner fixtures: Plan(optimize(sql, TPCH_SCHEMA, leave_tables_isolated=True))
for every TPC-H query, dumped canonically (step ids stripped, dependencies sorted, since
Python orders them by set iteration).

    python tools/gen_planner_fixtures.py
"""

import os
import re
import sys
import warnings

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SG = os.path.join(ROOT, ".repos", "sqlglot")
sys.path.insert(0, SG)
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
try:
    import dateutil.relativedelta  # noqa: F401
except ImportError:
    sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), "pyshim"))
warnings.filterwarnings("ignore")

import logging  # noqa: E402

logging.getLogger("sqlglot").setLevel(logging.CRITICAL)

from gen_meta import mbt_str  # noqa: E402

from sqlglot.optimizer import optimize  # noqa: E402
from sqlglot.planner import Plan  # noqa: E402
from tests.helpers import TPCH_SCHEMA, load_sql_fixture_pairs  # noqa: E402

OUT = os.path.join(ROOT, "src", "planner_tests")

EXTRA = [
    "SELECT a, SUM(b) AS s FROM x GROUP BY a HAVING SUM(b) > 1 ORDER BY s DESC LIMIT 10",
    "SELECT DISTINCT a FROM x ORDER BY a",
    "SELECT a FROM x UNION SELECT b AS a FROM y",
    "WITH t AS (SELECT a FROM x) SELECT t.a FROM t JOIN y ON t.a = y.b",
    "SELECT AVG(a) AS avg_a, AVG(b) AS avg_b FROM x",
]
EXTRA_SCHEMA = {"x": {"a": "int", "b": "int"}, "y": {"b": "int", "c": "int"}}


def canonical(step, level=0):
    indent = "  " * level
    text = step.to_s(level)
    # strip the dependencies and render them canonically
    lines = text.split("\n")
    nested = f"{indent}    "
    head = []
    for line in lines:
        if line == f"{nested}Dependencies:":
            break
        head.append(line)
    head = [re.sub(r" \(\d+\)$", "", h) for h in head]
    deps = sorted(canonical(d, level + 1) for d in step.dependencies)
    if deps:
        head.append(f"{nested}Dependencies:")
        head.extend("  " + d for d in deps)
    return "\n".join(head)


def main():
    records = []
    for _, sql, _ in load_sql_fixture_pairs("optimizer/tpc-h/tpc-h.sql"):
        plan = Plan(optimize(sql, TPCH_SCHEMA, leave_tables_isolated=True))
        records.append(("tpch", sql, canonical(plan.root)))
    for sql in EXTRA:
        plan = Plan(optimize(sql, EXTRA_SCHEMA, leave_tables_isolated=True))
        records.append(("extra", sql, canonical(plan.root)))

    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, "fixture_planner_test.mbt"), "w") as f:
        f.write("// Code generated by tools/gen_planner_fixtures.py. DO NOT EDIT.\n\n")
        f.write("///|\nlet planner_fixtures : Array[String] = [\n")
        for schema, sql, out in records:
            f.write(f"  {mbt_str(schema)},\n  {mbt_str(sql)},\n  {mbt_str(out)},\n")
        f.write("]\n\n")
        f.write(f"///|\nlet tpch_schema_json : String = {mbt_str(__import__('json').dumps(TPCH_SCHEMA))}\n\n")
        f.write(f"///|\nlet extra_schema_json : String = {mbt_str(__import__('json').dumps(EXTRA_SCHEMA))}\n")
    print("plans:", len(records))


if __name__ == "__main__":
    main()
