"""Scaffold MoonBit dialect packages (src/dialects/<name>) and the dialect registry.

Existing hand-written files are never overwritten; only moon.pkg, dialect.mbt and the
dialect registry package `bobzhang/sqlglot/dialects` (src/dialects/registry.mbt,
src/dialects/moon.pkg) are regenerated. The facade (`bobzhang/sqlglot`) re-exports the
registry; packages that need all dialects registered without depending on the facade
(e.g. the executor) import the registry package directly.
"""

import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIALECTS = os.path.join(ROOT, "src", "dialects")


def parent_of(name):
    with open(os.path.join(DIALECTS, name, "gen_config.mbt")) as f:
        return re.search(r"Parent dialect: (\w+)", f.read()).group(1)


def write(path, content, overwrite=True):
    if not overwrite and os.path.exists(path):
        return
    with open(path, "w") as f:
        f.write(content)


STUBS = {
    "tokenizer.mbt": ("configure_tokenizer", "Tokenizer"),
    "parser.mbt": ("configure_parser", "Parser"),
    "generator.mbt": ("configure_generator", "Generator"),
}


def main():
    names = sorted(
        d for d in os.listdir(DIALECTS) if os.path.exists(os.path.join(DIALECTS, d, "gen_config.mbt"))
    )
    for name in names:
        parent = parent_of(name)
        pkg_dir = os.path.join(DIALECTS, name)
        imports = ['  "bobzhang/sqlglot/core",']
        # Only import @set when the package's sources actually use it (an unused import
        # is a warning).
        uses_set = any(
            "@set." in open(os.path.join(pkg_dir, f)).read()
            for f in os.listdir(pkg_dir)
            if f.endswith(".mbt")
        )
        if uses_set:
            imports.append('  "moonbitlang/core/set",')
        if parent != "base":
            imports.append(f'  "bobzhang/sqlglot/dialects/{parent}",')
        # Keep any extra imports added by hand (e.g. spark importing hive for explicit
        # super(HiveGenerator, ...) calls); only ensure the required ones are present.
        pkg_path = os.path.join(pkg_dir, "moon.pkg")
        if os.path.exists(pkg_path):
            existing = re.findall(r'^\s*"[^"]+",?\s*$', open(pkg_path).read(), re.M)
            for line in existing:
                line = "  " + line.strip().rstrip(",") + ","
                if line == '  "moonbitlang/core/set",':
                    continue
                if line not in imports:
                    imports.append(line)
        write(pkg_path, "import {\n" + "\n".join(imports) + "\n}\n")
        parent_expr = "@core.base_dialect()" if parent == "base" else f"@{parent}.dialect()"
        write(
            os.path.join(pkg_dir, "dialect.mbt"),
            f"""// Code generated by tools/gen_dialect_pkgs.py. DO NOT EDIT.
// Port of sqlglot/dialects/{name}.py (configuration lives in gen_config.mbt, hand-written
// overrides in tokenizer.mbt, parser.mbt and generator.mbt).

///|
let dialect_cell : Ref[@core.Dialect?] = Ref(None)

///|
/// Importing this package registers the dialect under its name.
fn init {{
  @core.register_dialect("{name}", dialect)
}}

///|
/// The `{name}` dialect (a subclass of `{parent}`).
pub fn dialect() -> @core.Dialect {{
  match dialect_cell.val {{
    Some(d) => d
    None => {{
      let d = @core.Dialect::subclass({parent_expr}, "{name}", configure)
      dialect_cell.val = Some(d)
      d
    }}
  }}
}}

///|
fn configure(d : @core.Dialect) -> Unit {{
  apply_dialect_config(d.cfg)
  apply_tokenizer_config(d.tokenizer)
  apply_parser_config(d.parser_cfg)
  apply_generator_config(d.gen_cfg)
  configure_tokenizer(d)
  configure_parser(d)
  configure_generator(d)
}}
""",
        )
        for fname, (fn, what) in STUBS.items():
            write(
                os.path.join(pkg_dir, fname),
                f"""// {what} overrides for the {name} dialect.

///|
fn configure_{fn.split('_')[1]}(d : @core.Dialect) -> Unit {{
  ignore(d)
}}
""",
                overwrite=False,
            )

    # dialect registry package
    imports = ['  "bobzhang/sqlglot/core",'] + [
        f'  "bobzhang/sqlglot/dialects/{n}",' for n in names
    ]
    write(os.path.join(DIALECTS, "moon.pkg"), "import {\n" + "\n".join(imports) + "\n}\n")
    regs = "\n".join(f'  @core.register_dialect("{n}", @{n}.dialect)' for n in names)
    write(
        os.path.join(DIALECTS, "registry.mbt"),
        f"""// Code generated by tools/gen_dialect_pkgs.py. DO NOT EDIT.

///|
fn init {{
  register_dialects()
}}

///|
/// Registers all built-in dialects with the core dialect registry. Called automatically
/// when this package is initialized; safe to call again.
pub fn register_dialects() -> Unit {{
{regs}
}}

///|
/// Names of all built-in dialects.
pub let dialect_names : Array[String] = [{", ".join(f'"{n}"' for n in names)}]

///|
/// Looks up a dialect by name (`""` is the base sqlglot dialect); all built-in dialects
/// are registered.
pub fn dialect(name : String) -> @core.Dialect raise @core.SqlglotError {{
  @core.Dialect::get_or_raise(name)
}}
""",
    )


if __name__ == "__main__":
    main()
