"""Scaffold MoonBit dialect packages (src/dialects/<name>) and the facade registry.

Existing hand-written files are never overwritten; only moon.pkg, dialect.mbt and the
facade registry (src/registry.mbt, src/moon.pkg) are regenerated.
"""

import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIALECTS = os.path.join(ROOT, "src", "dialects")


def parent_of(name):
    with open(os.path.join(DIALECTS, name, "gen_config.mbt")) as f:
        return re.search(r"Parent dialect: (\w+)", f.read()).group(1)


def write(path, content, overwrite=True):
    if not overwrite and os.path.exists(path):
        return
    with open(path, "w") as f:
        f.write(content)


STUBS = {
    "tokenizer.mbt": ("configure_tokenizer", "Tokenizer"),
    "parser.mbt": ("configure_parser", "Parser"),
    "generator.mbt": ("configure_generator", "Generator"),
}


def main():
    names = sorted(
        d for d in os.listdir(DIALECTS) if os.path.exists(os.path.join(DIALECTS, d, "gen_config.mbt"))
    )
    for name in names:
        parent = parent_of(name)
        pkg_dir = os.path.join(DIALECTS, name)
        imports = ['  "hongbozhang/sqlglot/core",', '  "moonbitlang/core/set",']
        if parent != "base":
            imports.append(f'  "hongbozhang/sqlglot/dialects/{parent}",')
        write(
            os.path.join(pkg_dir, "moon.pkg"),
            "import {\n" + "\n".join(imports) + "\n}\n\nwarnings = \"-79-15\"\n",
        )
        parent_expr = "@core.base_dialect()" if parent == "base" else f"@{parent}.dialect()"
        write(
            os.path.join(pkg_dir, "dialect.mbt"),
            f"""// Code generated by tools/gen_dialect_pkgs.py. DO NOT EDIT.
// Port of sqlglot/dialects/{name}.py (configuration lives in gen_config.mbt, hand-written
// overrides in tokenizer.mbt, parser.mbt and generator.mbt).

///|
let dialect_cell : Ref[@core.Dialect?] = Ref(None)

///|
/// Importing this package registers the dialect under its name.
fn init {{
  @core.register_dialect("{name}", dialect)
}}

///|
/// The `{name}` dialect (a subclass of `{parent}`).
pub fn dialect() -> @core.Dialect {{
  match dialect_cell.val {{
    Some(d) => d
    None => {{
      let d = @core.Dialect::subclass({parent_expr}, "{name}", configure)
      dialect_cell.val = Some(d)
      d
    }}
  }}
}}

///|
fn configure(d : @core.Dialect) -> Unit {{
  apply_dialect_config(d.cfg)
  apply_tokenizer_config(d.tokenizer)
  apply_parser_config(d.parser_cfg)
  apply_generator_config(d.gen_cfg)
  configure_tokenizer(d)
  configure_parser(d)
  configure_generator(d)
}}
""",
        )
        for fname, (fn, what) in STUBS.items():
            write(
                os.path.join(pkg_dir, fname),
                f"""// {what} overrides for the {name} dialect.

///|
fn configure_{fn.split('_')[1]}(d : @core.Dialect) -> Unit {{
  ignore(d)
}}
""",
                overwrite=False,
            )

    # facade
    src = os.path.join(ROOT, "src")
    imports = ['  "hongbozhang/sqlglot/core",'] + [
        f'  "hongbozhang/sqlglot/dialects/{n}",' for n in names
    ]
    write(os.path.join(src, "moon.pkg"), "import {\n" + "\n".join(imports) + "\n}\n")
    regs = "\n".join(f'  @core.register_dialect("{n}", @{n}.dialect)' for n in names)
    write(
        os.path.join(src, "registry.mbt"),
        f"""// Code generated by tools/gen_dialect_pkgs.py. DO NOT EDIT.

///|
fn init {{
  register_dialects()
}}

///|
/// Registers all built-in dialects with the core dialect registry. Called automatically
/// when this package is initialized; safe to call again.
pub fn register_dialects() -> Unit {{
{regs}
}}

///|
/// Names of all built-in dialects.
pub let dialect_names : Array[String] = [{", ".join(f'"{n}"' for n in names)}]
""",
    )


if __name__ == "__main__":
    main()
