"""Record how Python sqlglot treats missing / None / False / 0 / "" / [] (and SQL NULL)
argument values, for src/unit_tests_b/none_matrix_test.mbt.

For every (case, value) pair, an expression is built with the argument set to the value
(or left out for "missing"), and the following observations are recorded:

    keys        sorted(e.args)                      (construction)
    get         e.args.get(key)                     (repr, see `show`)
    truthy      bool(e.args.get(key))               (Expr::has)
    text        e.text(key)
    eq_missing  e == <the same expression without the argument>
    hash_missing  hash(e) == hash(<without the argument>)
    copy_keys / copy_eq      after e.copy()
    serde_keys / serde_get / serde_eq   after load(dump(e))
    sql         e.sql()
    set_keys / set_get       after <without the argument>.set(key, value)

Usage: python tools/gen_none_matrix.py   (writes src/unit_tests_b/fixture_none_matrix_test.mbt)
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SG = os.path.join(ROOT, ".repos", "sqlglot")
sys.path.insert(0, SG)
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from gen_meta import mbt_str  # noqa: E402

from sqlglot import exp  # noqa: E402
from sqlglot.serde import dump, load  # noqa: E402

OUT = os.path.join(ROOT, "src", "unit_tests_b", "fixture_none_matrix_test.mbt")

MISSING = object()

SCALARS = {
    "missing": MISSING,
    "None": None,
    "False": False,
    "True": True,
    "0": 0,
    "1": 1,
    "''": "",
    "[]": [],
    "NULL": "NULL",  # replaced by exp.Null() below
}

LISTS = {
    "missing": MISSING,
    "None": None,
    "[]": [],
    "[None]": [None],
    "[1, None]": ["1", None],
    "[False]": [False],
    "[1]": ["1"],
    # elements that generate no SQL: Python's generator skips them but still counts
    # them when placing separators
    "[1, '']": ["1", ""],
    "['', 1]": ["", "1"],
    "[1, NULL]": ["1", "NULL"],
}


def value_of(tag, table):
    v = table[tag]
    if tag == "NULL":
        return exp.Null()
    if isinstance(v, list):
        return [
            exp.Literal.number(1) if x == "1" else exp.Null() if x == "NULL" else x for x in v
        ]
    return v


# case name -> (builder(**kwargs) -> Expr, key, values table)
CASES = {
    "column.db": (
        lambda **kw: exp.Column(this=exp.to_identifier("b"), table=exp.to_identifier("a"), **kw),
        "db",
        SCALARS,
    ),
    "ordered.desc": (
        lambda **kw: exp.Ordered(this=exp.column("x"), nulls_first=False, **kw),
        "desc",
        SCALARS,
    ),
    "identifier.quoted": (lambda **kw: exp.Identifier(this="x", **kw), "quoted", SCALARS),
    "literal.is_string": (lambda **kw: exp.Literal(this="1", **kw), "is_string", SCALARS),
    "tuple.expressions": (lambda **kw: exp.Tuple(**kw), "expressions", LISTS),
}


def show(v):
    if v is MISSING:
        return "missing"
    if isinstance(v, exp.Expr):
        return f"node:{type(v).__name__}"
    if isinstance(v, list):
        return "[" + ", ".join(show(x) for x in v) + "]"
    if isinstance(v, str):
        return repr(v)
    return repr(v)


def observe(build, key, value):
    kwargs = {} if value is MISSING else {key: value}
    e = build(**kwargs)
    base = build()
    obs = {}
    obs["keys"] = ",".join(sorted(e.args))
    obs["get"] = show(e.args.get(key, MISSING))
    obs["truthy"] = str(bool(e.args.get(key)))
    obs["text"] = repr(e.text(key))
    obs["eq_missing"] = str(e == base)
    obs["hash_missing"] = str(hash(e) == hash(base))
    c = e.copy()
    obs["copy_keys"] = ",".join(sorted(c.args))
    obs["copy_eq"] = str(c == e)
    loaded = load(dump(e))
    obs["serde_keys"] = ",".join(sorted(loaded.args))
    obs["serde_get"] = show(loaded.args.get(key, MISSING))
    obs["serde_eq"] = str(loaded == e)
    try:
        obs["sql"] = e.sql()
    except Exception as ex:  # noqa: BLE001
        obs["sql"] = f"<{type(ex).__name__}>"
    if value is not MISSING:
        s = build()
        # a fresh value: `value` may already be attached to `e`
        s.set(key, value.copy() if isinstance(value, exp.Expr) else (
            [x.copy() if isinstance(x, exp.Expr) else x for x in value]
            if isinstance(value, list) else value))
        obs["set_keys"] = ",".join(sorted(s.args))
        obs["set_get"] = show(s.args.get(key, MISSING))
    return obs


def main():
    rows = []
    for case, (build, key, table) in CASES.items():
        for tag in table:
            obs = observe(build, key, value_of(tag, table))
            rows.append((case, tag, "; ".join(f"{k}={v}" for k, v in obs.items())))
    with open(OUT, "w") as f:
        f.write("// Code generated by tools/gen_none_matrix.py. DO NOT EDIT.\n\n")
        f.write("///|\n/// (case, value, observations) triples recorded from Python sqlglot.\n")
        f.write("let none_matrix_fixtures : Array[String] = [\n")
        for row in rows:
            f.write("  " + ", ".join(mbt_str(x) for x in row) + ",\n")
        f.write("]\n")
    print(f"{len(rows)} rows")


if __name__ == "__main__":
    main()
