"""Generate MoonBit metadata tables from the Python sqlglot sources.

Usage: python3 tools/gen_meta.py  (expects the Python sqlglot checkout in .repos/sqlglot)
"""

import os
import sys
import warnings

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, ".repos", "sqlglot"))
warnings.filterwarnings("ignore")

from sqlglot import exp  # noqa: E402
from sqlglot.tokenizer_core import TokenType  # noqa: E402
from sqlglot.helper import camel_to_snake_case  # noqa: E402

OUT = os.path.join(ROOT, "src", "core")


def mbt_str(s):
    out = ['"']
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif ord(ch) < 32:
            out.append("\\u{%x}" % ord(ch))
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def kind_name(cls_name):
    if cls_name.startswith("_"):
        return "Priv" + cls_name[1:]
    return cls_name


def all_classes():
    seen = []

    def walk(c):
        for s in c.__subclasses__():
            if s not in seen:
                seen.append(s)
                walk(s)

    walk(exp.Expr)
    return seen


POLY_PROPS = [
    "name", "output_name", "selects", "named_selects", "is_star", "to_py", "unnest",
    "alias_or_name", "this", "is_type", "unit", "ctes", "parts", "alias", "kind",
    "side", "method", "db", "catalog", "table", "columns", "left", "right", "is_number",
    "is_string", "is_int", "to",
]


def gen_kinds():
    classes = all_classes()
    classes.sort(key=lambda c: c.__name__)
    idx = {c: i for i, c in enumerate(classes)}
    lines = ["// Code generated by tools/gen_meta.py. DO NOT EDIT.", ""]
    lines.append("///|")
    lines.append("/// Every expression class of sqlglot, including abstract traits.")
    lines.append("pub(all) enum Kind {")
    for c in classes:
        lines.append(f"  {kind_name(c.__name__)}")
    lines.append("} derive(Eq, Hash)")
    lines.append("")
    lines.append("///|")
    lines.append("pub fn Kind::id(self : Kind) -> Int {")
    lines.append("  match self {")
    for c in classes:
        lines.append(f"    {kind_name(c.__name__)} => {idx[c]}")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("///|")
    lines.append("pub let all_kinds : FixedArray[Kind] = [")
    for c in classes:
        lines.append(f"  {kind_name(c.__name__)},")
    lines.append("]")
    lines.append("")
    lines.append("///|")
    lines.append("let kind_names : FixedArray[String] = [")
    for c in classes:
        lines.append(f"  {mbt_str(c.__name__)},")
    lines.append("]")
    lines.append("")
    # ancestors
    lines.append("///|")
    lines.append("let kind_ancestors : FixedArray[FixedArray[Int]] = [")
    for c in classes:
        anc = [idx[a] for a in c.__mro__[1:] if a in idx]
        lines.append("  [" + ", ".join(map(str, anc)) + "],")
    lines.append("]")
    lines.append("")
    # arg types
    lines.append("///|")
    lines.append("let kind_arg_types : FixedArray[FixedArray[(String, Bool)]] = [")
    for c in classes:
        at = getattr(c, "arg_types", {})
        items = ", ".join(f"({mbt_str(k)}, {'true' if v else 'false'})" for k, v in at.items())
        lines.append(f"  [{items}],")
    lines.append("]")
    lines.append("")
    # flags
    flags = [
        ("is_var_len_args", "kind_var_len"),
        ("is_subquery", "kind_is_subquery"),
        ("is_cast", "kind_is_cast"),
        ("is_data_type", "kind_is_data_type"),
        ("is_primitive", "kind_is_primitive"),
        ("_hash_raw_args", "kind_hash_raw_args"),
    ]
    for attr, name in flags:
        vals = [bool(getattr(c, attr, False)) for c in classes]
        lines.append("///|")
        lines.append(f"let {name} : FixedArray[Bool] = [")
        for i in range(0, len(vals), 16):
            lines.append("  " + ", ".join("true" if v else "false" for v in vals[i : i + 16]) + ",")
        lines.append("]")
        lines.append("")
    lines.append("///|")
    lines.append("let kind_var_len_arg_key : FixedArray[String] = [")
    for c in classes:
        lines.append(f"  {mbt_str(getattr(c, 'var_len_arg_key', 'expressions'))},")
    lines.append("]")
    lines.append("")
    # concrete (non trait) classes
    lines.append("///|")
    lines.append("let kind_is_trait : FixedArray[Bool] = [")
    for c in classes:
        is_trait = not issubclass(c, exp.Expression)
        lines.append(f"  {'true' if is_trait else 'false'},")
    lines.append("]")
    lines.append("")
    # sql names for functions
    lines.append("///|")
    lines.append("let kind_sql_names : FixedArray[FixedArray[String]] = [")
    for c in classes:
        names = []
        if issubclass(c, exp.Func) and issubclass(c, exp.Expression):
            try:
                names = c.sql_names()
            except Exception:
                names = []
        lines.append("  [" + ", ".join(mbt_str(n) for n in names) + "],")
    lines.append("]")
    lines.append("")
    # MRO owners of polymorphic properties/methods
    for prop in POLY_PROPS:
        lines.append("///|")
        lines.append(f"let kind_owner_{prop} : FixedArray[Int] = [")
        vals = []
        for c in classes:
            owner = -1
            for a in c.__mro__:
                if prop in a.__dict__:
                    owner = idx.get(a, -1)
                    break
            vals.append(owner)
        for i in range(0, len(vals), 16):
            lines.append("  " + ", ".join(map(str, vals[i : i + 16])) + ",")
        lines.append("]")
        lines.append("")
        lines.append("///|")
        lines.append(f"/// The class in the MRO of `self` that defines `{prop}` (None for the base `Expression`).")
        lines.append(f"pub fn Kind::owner_{prop}(self : Kind) -> Kind? {{")
        lines.append(f"  let o = kind_owner_{prop}[self.id()]")
        lines.append("  if o < 0 { None } else { Some(all_kinds[o]) }")
        lines.append("}")
        lines.append("")
    with open(os.path.join(OUT, "gen_kinds.mbt"), "w") as f:
        f.write("\n".join(lines))


def gen_token_types():
    names = [t.name for t in TokenType]
    lines = ["// Code generated by tools/gen_meta.py. DO NOT EDIT.", ""]
    lines.append("///|")
    lines.append("pub(all) enum TokenType {")
    for n in names:
        lines.append(f"  {n}")
    lines.append("} derive(Eq, Hash, Compare)")
    lines.append("")
    lines.append("///|")
    lines.append("pub fn TokenType::id(self : TokenType) -> Int {")
    lines.append("  match self {")
    for i, n in enumerate(names):
        lines.append(f"    {n} => {i}")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("///|")
    lines.append("pub let all_token_types : FixedArray[TokenType] = [")
    for n in names:
        lines.append(f"  {n},")
    lines.append("]")
    lines.append("")
    lines.append("///|")
    lines.append("let token_type_names : FixedArray[String] = [")
    for n in names:
        lines.append(f"  {mbt_str(n)},")
    lines.append("]")
    lines.append("")
    with open(os.path.join(OUT, "gen_token_types.mbt"), "w") as f:
        f.write("\n".join(lines))


def gen_dtypes():
    DT = exp.DataType
    names = [t.name for t in exp.DType]
    values = [t.value for t in exp.DType]
    lines = ["// Code generated by tools/gen_meta.py. DO NOT EDIT.", ""]
    lines.append("///|")
    lines.append("pub(all) enum DType {")
    for n in names:
        lines.append(f"  {n}")
    lines.append("} derive(Eq, Hash, Compare)")
    lines.append("")
    lines.append("///|")
    lines.append("pub fn DType::id(self : DType) -> Int {")
    lines.append("  match self {")
    for i, n in enumerate(names):
        lines.append(f"    {n} => {i}")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("///|")
    lines.append("pub let all_dtypes : FixedArray[DType] = [")
    for n in names:
        lines.append(f"  {n},")
    lines.append("]")
    lines.append("")
    lines.append("///|")
    lines.append("let dtype_names : FixedArray[String] = [")
    for n in names:
        lines.append(f"  {mbt_str(n)},")
    lines.append("]")
    lines.append("")
    lines.append("///|")
    lines.append("let dtype_values : FixedArray[String] = [")
    for v in values:
        lines.append(f"  {mbt_str(v)},")
    lines.append("]")
    lines.append("")
    for attr in sorted(a for a in dir(DT) if a.endswith("_TYPES") or a.endswith("TYPES") and a.isupper()):
        v = getattr(DT, attr)
        if not isinstance(v, (set, frozenset)):
            continue
        members = sorted(x.name for x in v)
        lines.append("///|")
        lines.append(f"pub let dtype_{attr.lower()} : Array[DType] = [")
        for m in members:
            lines.append(f"  {m},")
        lines.append("]")
        lines.append("")
    with open(os.path.join(OUT, "gen_dtypes.mbt"), "w") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    gen_kinds()
    gen_token_types()
    gen_dtypes()
