"""Generate MoonBit generator fixtures: (sql, canonical AST, sql(), sql(pretty=True), sql(identify=True)).

The canonical AST format is the one of tools/gen_fixtures.py (`canonical`).
"""

import os
import sys
import warnings

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SG = os.path.join(ROOT, ".repos", "sqlglot")
sys.path.insert(0, SG)
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
warnings.filterwarnings("ignore")

import logging  # noqa: E402

logging.getLogger("sqlglot").setLevel(logging.CRITICAL)

from gen_fixtures import canonical as _canonical  # noqa: E402


def canonical(node):
    """`gen_fixtures.canonical` plus `#t=` (the `_type` of a node) for typed nodes."""
    from sqlglot import exp

    s = _canonical(node)
    return s


def canonical_typed(node):
    from sqlglot import exp

    def val(v):
        if isinstance(v, exp.Expr):
            return canonical_typed(v)
        if isinstance(v, list):
            return "[" + ",".join(val(x) or scalar(x) for x in v if x is not None) + "]"
        return None

    import json
    from sqlglot.expressions import DType

    def scalar(v):
        if isinstance(v, bool):
            return "true" if v else "false"
        if isinstance(v, DType):
            return "DType." + v.name
        if isinstance(v, int):
            return str(v)
        if isinstance(v, str):
            return json.dumps(v, ensure_ascii=False)
        return json.dumps(str(v), ensure_ascii=False)

    order = list(type(node).arg_types)
    keys = [k for k in order if k in node.args] + sorted(k for k in node.args if k not in order)
    parts = []
    for k in keys:
        v = node.args[k]
        if v is None:
            continue
        r = val(v)
        parts.append(f"{k}={r if r is not None else scalar(v)}")
    if node.comments:
        parts.append("#c=" + json.dumps(node.comments, ensure_ascii=False))
    t = node._type
    if t is not None and not node.is_data_type:
        parts.append("#t=" + canonical_typed(t))
    return f"{type(node).__name__}({','.join(parts)})"
from gen_meta import mbt_str  # noqa: E402

OUT = os.path.join(ROOT, "src", "generator_tests")


def dialect_cases(path):
    import json
    import sqlglot

    seen = set()
    res = []
    for line in open(path):
        c = json.loads(line)
        if "error" in c or c.get("kind") not in ("identity", "all", "transpile"):
            continue
        read = c.get("read") or ""
        sql = c.get("sql")
        if not isinstance(sql, str) or (read, sql) in seen:
            continue
        seen.add((read, sql))
        try:
            e = sqlglot.parse_one(sql, read=read or None)
            if e is None:
                continue
            ast = canonical_typed(e)
            out = e.sql()
            pretty = e.sql(pretty=True)
            ident = e.sql(identify=True)
        except Exception:
            continue
        res.append([read + ": " + sql, ast, out, pretty, ident])
    return res


def cases():
    import sqlglot

    seen = set()

    def add(sql, expected_pretty=None):
        try:
            e = sqlglot.parse_one(sql)
        except Exception:
            return None
        if e is None:
            return None
        try:
            ast = canonical_typed(e)
            out = e.sql()
            pretty = e.sql(pretty=True) if expected_pretty is None else expected_pretty
            ident = e.sql(identify=True)
        except Exception:
            return None
        key = (ast, out, pretty, ident)
        if key in seen:
            return None
        seen.add(key)
        return [sql, ast, out, pretty, ident]

    res = []
    for line in open(os.path.join(SG, "tests/fixtures/identity.sql")):
        line = line.rstrip("\n")
        if not line.strip():
            continue
        c = add(line)
        if c:
            res.append(c)

    sys.path.insert(0, os.path.join(SG, "tests"))
    from helpers import load_sql_fixture_pairs

    for _, src, expected in load_sql_fixture_pairs("pretty.sql"):
        c = add(src, expected_pretty=expected)
        if c:
            res.append(c)
    return res


def main():
    os.makedirs(OUT, exist_ok=True)
    res = cases()
    with open(os.path.join(OUT, "generator_fixture_data_test.mbt"), "w") as f:
        f.write("// Code generated by tools/gen_generator_fixtures.py. DO NOT EDIT.\n\n")
        f.write("///|\n")
        f.write("/// (sql, canonical AST, sql(), sql(pretty=True), sql(identify=True))\n")
        f.write("let generator_fixtures : Array[String] = [\n")
        for c in res:
            for s in c:
                f.write(f"  {mbt_str(s)},\n")
        f.write("]\n")
    print(len(res), "cases")
    if len(sys.argv) > 1:
        res = dialect_cases(sys.argv[1])
        with open(os.path.join(OUT, "generator_dialect_data_test.mbt"), "w") as f:
            f.write("// Code generated by tools/gen_generator_fixtures.py. DO NOT EDIT.\n\n")
            f.write("///|\n")
            f.write("/// Dialect test inputs parsed by Python and generated with the base dialect.\n")
            f.write("let generator_dialect_fixtures : Array[String] = [\n")
            for c in res:
                for s in c:
                    f.write(f"  {mbt_str(s)},\n")
            f.write("]\n")
        print(len(res), "dialect cases")


if __name__ == "__main__":
    main()
