"""Generate fixture data for the ported top-level module tests in src/toplevel_tests
(tests/test_serde.py and friends).

Writes src/toplevel_tests/fixture_serde_test.mbt with
  * `serde_identity`: the statements of tests/fixtures/identity.sql (load_sql_fixtures)
  * `serde_python_dumps`: (sql, json.dumps(parse_one(sql).dump())) pairs for every
    DUMP_STRIDE-th identity statement, used to check that payloads produced by Python
    load in MoonBit (and vice versa).

Run with the scratchpad venv python; env SQLGLOT_REPO points at the Python checkout
(default <root>/.repos/sqlglot).
"""

import json
import os
import sys
import warnings

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SG = os.environ.get("SQLGLOT_REPO", os.path.join(ROOT, ".repos", "sqlglot"))
sys.path.insert(0, SG)
sys.path.insert(0, os.path.join(ROOT, "tools", "pyshim"))
warnings.filterwarnings("ignore")

from gen_meta import mbt_str  # noqa: E402
from sqlglot import parse_one  # noqa: E402
from tests.helpers import load_sql_fixtures  # noqa: E402

OUT = os.path.join(ROOT, "src", "toplevel_tests", "fixture_serde_test.mbt")
DUMP_STRIDE = 7


def write_array(f, name, items):
    f.write("///|\n")
    f.write(f"let {name} : Array[String] = [\n")
    for item in items:
        f.write(f"  {mbt_str(item)},\n")
    f.write("]\n\n")


def main():
    identity = list(load_sql_fixtures("identity.sql"))
    dumps = []
    for i, sql in enumerate(identity):
        if i % DUMP_STRIDE:
            continue
        payload = json.dumps(parse_one(sql).dump(), ensure_ascii=False, separators=(",", ":"))
        dumps += [sql, payload]
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Code generated by tools/gen_toplevel_fixtures.py. DO NOT EDIT.\n\n")
        write_array(f, "serde_identity", identity)
        write_array(f, "serde_python_dumps", dumps)


if __name__ == "__main__":
    main()
