"""Generate fixture data for the ported Python unit tests in src/unit_tests_a.

Reads tests/fixtures/{identity,partial,pretty}.sql, tests/fixtures/jsonpath/cts.json and
the `overrides` dict of tests/test_jsonpath.py::test_cts_file from the Python sqlglot
checkout (env SQLGLOT_REPO, default <root>/.repos/sqlglot).
"""

import ast
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SG = os.environ.get("SQLGLOT_REPO", os.path.join(ROOT, ".repos", "sqlglot"))
sys.path.insert(0, SG)

from gen_meta import mbt_str  # noqa: E402
from tests.helpers import load_sql_fixture_pairs, load_sql_fixtures  # noqa: E402

OUT = os.path.join(ROOT, "src", "unit_tests_a", "fixtures_test.mbt")


def write_array(f, name, items):
    f.write("///|\n")
    f.write(f"let {name} : Array[String] = [\n")
    for item in items:
        f.write(f"  {mbt_str(item)},\n")
    f.write("]\n\n")


def cts_overrides():
    src = open(os.path.join(SG, "tests", "test_jsonpath.py"), encoding="utf-8").read()
    for node in ast.walk(ast.parse(src)):
        if (
            isinstance(node, ast.Assign)
            and isinstance(node.targets[0], ast.Name)
            and node.targets[0].id == "overrides"
        ):
            return ast.literal_eval(node.value)
    raise RuntimeError("overrides not found")


def main():
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Code generated by tools/gen_unit_fixtures.py. DO NOT EDIT.\n\n")
        write_array(f, "identity_fixtures", list(load_sql_fixtures("identity.sql")))
        write_array(f, "partial_fixtures", list(load_sql_fixtures("partial.sql")))
        pretty = []
        for meta, sql, expected in load_sql_fixture_pairs("pretty.sql"):
            assert not meta, meta
            pretty += [sql, expected]
        write_array(f, "pretty_fixtures", pretty)

        with open(os.path.join(SG, "tests", "fixtures", "jsonpath", "cts.json"), encoding="utf-8") as fh:
            tests = json.load(fh)["tests"]
        # (name, selector, "1" if invalid_selector else "0")
        cts = []
        for test in tests:
            cts += [test["name"], test["selector"], "1" if test.get("invalid_selector") else "0"]
        write_array(f, "cts_fixtures", cts)

        overrides = []
        for k, v in cts_overrides().items():
            overrides += [k, v]
        write_array(f, "cts_overrides", overrides)


if __name__ == "__main__":
    main()
