"""Generate MoonBit metadata tables from the Python sqlglot sources.

Usage: python3 tools/gen_meta.py  (expects the Python sqlglot checkout in .repos/sqlglot)
"""

import os
import sys
import warnings

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, ".repos", "sqlglot"))
warnings.filterwarnings("ignore")

from sqlglot import exp  # noqa: E402
from sqlglot.tokenizer_core import TokenType  # noqa: E402
from sqlglot.helper import camel_to_snake_case  # noqa: E402

OUT = os.path.join(ROOT, "src", "core")


def mbt_str(s):
    out = ['"']
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif ord(ch) < 32:
            out.append("\\u{%x}" % ord(ch))
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def kind_name(cls_name):
    if cls_name.startswith("_"):
        return "Priv" + cls_name[1:]
    return cls_name


def all_classes():
    seen = []

    def walk(c):
        for s in c.__subclasses__():
            if s not in seen:
                seen.append(s)
                walk(s)

    walk(exp.Expr)
    return seen


POLY_PROPS = [
    "name", "output_name", "selects", "named_selects", "is_star", "to_py", "unnest",
    "alias_or_name", "this", "is_type", "unit", "ctes", "parts", "alias", "kind",
    "side", "method", "db", "catalog", "table", "columns", "left", "right", "is_number",
    "is_string", "is_int", "to",
]


def gen_kinds():
    classes = all_classes()
    classes.sort(key=lambda c: c.__name__)
    idx = {c: i for i, c in enumerate(classes)}
    lines = ["// Code generated by tools/gen_meta.py. DO NOT EDIT.", ""]
    lines.append("///|")
    lines.append("/// Every expression class of sqlglot, including abstract traits.")
    lines.append("pub(all) enum Kind {")
    for c in classes:
        lines.append(f"  {kind_name(c.__name__)}")
    lines.append("} derive(Eq, Hash)")
    lines.append("")
    lines.append("///|")
    lines.append("pub fn Kind::id(self : Kind) -> Int {")
    lines.append("  match self {")
    for c in classes:
        lines.append(f"    {kind_name(c.__name__)} => {idx[c]}")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("///|")
    lines.append("pub let all_kinds : FixedArray[Kind] = [")
    for c in classes:
        lines.append(f"  {kind_name(c.__name__)},")
    lines.append("]")
    lines.append("")
    lines.append("///|")
    lines.append("let kind_names : FixedArray[String] = [")
    for c in classes:
        lines.append(f"  {mbt_str(c.__name__)},")
    lines.append("]")
    lines.append("")
    # ancestors
    lines.append("///|")
    lines.append("let kind_ancestors : FixedArray[FixedArray[Int]] = [")
    for c in classes:
        anc = [idx[a] for a in c.__mro__[1:] if a in idx]
        lines.append("  [" + ", ".join(map(str, anc)) + "],")
    lines.append("]")
    lines.append("")
    # arg types
    lines.append("///|")
    lines.append("let kind_arg_types : FixedArray[FixedArray[(String, Bool)]] = [")
    for c in classes:
        at = getattr(c, "arg_types", {})
        items = ", ".join(f"({mbt_str(k)}, {'true' if v else 'false'})" for k, v in at.items())
        lines.append(f"  [{items}],")
    lines.append("]")
    lines.append("")
    # flags
    flags = [
        ("is_var_len_args", "kind_var_len"),
        ("is_subquery", "kind_is_subquery"),
        ("is_cast", "kind_is_cast"),
        ("is_data_type", "kind_is_data_type"),
        ("is_primitive", "kind_is_primitive"),
        ("_hash_raw_args", "kind_hash_raw_args"),
    ]
    for attr, name in flags:
        vals = [bool(getattr(c, attr, False)) for c in classes]
        lines.append("///|")
        lines.append(f"let {name} : FixedArray[Bool] = [")
        for i in range(0, len(vals), 16):
            lines.append("  " + ", ".join("true" if v else "false" for v in vals[i : i + 16]) + ",")
        lines.append("]")
        lines.append("")
    lines.append("///|")
    lines.append("let kind_var_len_arg_key : FixedArray[String] = [")
    for c in classes:
        lines.append(f"  {mbt_str(getattr(c, 'var_len_arg_key', 'expressions'))},")
    lines.append("]")
    lines.append("")
    # concrete (non trait) classes
    lines.append("///|")
    lines.append("let kind_is_trait : FixedArray[Bool] = [")
    for c in classes:
        is_trait = not issubclass(c, exp.Expression)
        lines.append(f"  {'true' if is_trait else 'false'},")
    lines.append("]")
    lines.append("")
    # sql names for functions
    lines.append("///|")
    lines.append("let kind_sql_names : FixedArray[FixedArray[String]] = [")
    for c in classes:
        names = []
        if issubclass(c, exp.Func) and issubclass(c, exp.Expression):
            try:
                names = c.sql_names()
            except Exception:
                names = []
        lines.append("  [" + ", ".join(mbt_str(n) for n in names) + "],")
    lines.append("]")
    lines.append("")
    # MRO owners of polymorphic properties/methods
    for prop in POLY_PROPS:
        lines.append("///|")
        lines.append(f"let kind_owner_{prop} : FixedArray[Int] = [")
        vals = []
        for c in classes:
            # Python attribute lookup: the first class in the MRO defining `prop`. The base
            # implementations (on `Expr` / `Expression`) map to -1, but traits listed after
            # `Expression` in the bases (e.g. `class Subquery(Expression, DerivedTable, Query)`)
            # still take part in the lookup.
            owner = -1
            for a in c.__mro__:
                if prop in a.__dict__:
                    owner = -1 if a in (exp.Expr, exp.Expression) else idx.get(a, -1)
                    break
            vals.append(owner)
        for i in range(0, len(vals), 16):
            lines.append("  " + ", ".join(map(str, vals[i : i + 16])) + ",")
        lines.append("]")
        lines.append("")
        lines.append("///|")
        lines.append(f"/// The class in the MRO of `self` that defines `{prop}` (None for the base `Expression`).")
        lines.append(f"pub fn Kind::owner_{prop}(self : Kind) -> Kind? {{")
        lines.append(f"  let o = kind_owner_{prop}[self.id()]")
        lines.append("  if o < 0 { None } else { Some(all_kinds[o]) }")
        lines.append("}")
        lines.append("")
    with open(os.path.join(OUT, "gen_kinds.mbt"), "w") as f:
        f.write("\n".join(lines))


def gen_token_types():
    names = [t.name for t in TokenType]
    lines = ["// Code generated by tools/gen_meta.py. DO NOT EDIT.", ""]
    lines.append("///|")
    lines.append("pub(all) enum TokenType {")
    for n in names:
        lines.append(f"  {n}")
    lines.append("} derive(Eq, Hash, Compare)")
    lines.append("")
    lines.append("///|")
    lines.append("pub fn TokenType::id(self : TokenType) -> Int {")
    lines.append("  match self {")
    for i, n in enumerate(names):
        lines.append(f"    {n} => {i}")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("///|")
    lines.append("pub let all_token_types : FixedArray[TokenType] = [")
    for n in names:
        lines.append(f"  {n},")
    lines.append("]")
    lines.append("")
    lines.append("///|")
    lines.append("let token_type_names : FixedArray[String] = [")
    for n in names:
        lines.append(f"  {mbt_str(n)},")
    lines.append("]")
    lines.append("")
    with open(os.path.join(OUT, "gen_token_types.mbt"), "w") as f:
        f.write("\n".join(lines))


def gen_dtypes():
    DT = exp.DataType
    names = [t.name for t in exp.DType]
    values = [t.value for t in exp.DType]
    lines = ["// Code generated by tools/gen_meta.py. DO NOT EDIT.", ""]
    lines.append("///|")
    lines.append("pub(all) enum DType {")
    for n in names:
        lines.append(f"  {n}")
    lines.append("} derive(Eq, Hash, Compare)")
    lines.append("")
    lines.append("///|")
    lines.append("pub fn DType::id(self : DType) -> Int {")
    lines.append("  match self {")
    for i, n in enumerate(names):
        lines.append(f"    {n} => {i}")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("///|")
    lines.append("pub let all_dtypes : FixedArray[DType] = [")
    for n in names:
        lines.append(f"  {n},")
    lines.append("]")
    lines.append("")
    lines.append("///|")
    lines.append("let dtype_names : FixedArray[String] = [")
    for n in names:
        lines.append(f"  {mbt_str(n)},")
    lines.append("]")
    lines.append("")
    lines.append("///|")
    lines.append("let dtype_values : FixedArray[String] = [")
    for v in values:
        lines.append(f"  {mbt_str(v)},")
    lines.append("]")
    lines.append("")
    for attr in sorted(a for a in dir(DT) if a.endswith("_TYPES") or a.endswith("TYPES") and a.isupper()):
        v = getattr(DT, attr)
        if not isinstance(v, (set, frozenset)):
            continue
        members = sorted(x.name for x in v)
        lines.append("///|")
        lines.append(f"pub let dtype_{attr.lower()} : Array[DType] = [")
        for m in members:
            lines.append(f"  {m},")
        lines.append("]")
        lines.append("")
    with open(os.path.join(OUT, "gen_dtypes.mbt"), "w") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    gen_kinds()
    gen_token_types()
    gen_dtypes()


# ---------------------------------------------------------------------------
# Tokenizer settings


def mbt_char(c):
    s = mbt_str(c)
    return "'" + s[1:-1].replace("'", "\\'").replace('\\"', '"') + "'"


def quote_specs(arr):
    out = []
    for item in arr:
        if isinstance(item, str):
            out.append(f"Same({mbt_str(item)})")
        else:
            out.append(f"Pair({mbt_str(item[0])}, {mbt_str(item[1])})")
    return "[" + ", ".join(out) + "]"


def tt_list(arr):
    return "[" + ", ".join(sorted(f"TokenType::{t.name}" for t in arr)) + "]"


def tokenizer_settings_full(cls, fn_name, pub=True):
    L = []
    L.append("///|")
    L.append(f"{'pub ' if pub else ''}fn {fn_name}() -> TokenizerSettings {{")
    L.append("  let single_tokens : Map[Char, TokenType] = {")
    for k, v in cls.SINGLE_TOKENS.items():
        assert len(k) == 1, k
        L.append(f"    {mbt_char(k)}: {v.name},")
    L.append("  }")
    L.append("  let keywords : Map[String, TokenType] = {")
    for k, v in cls.KEYWORDS.items():
        L.append(f"    {mbt_str(k)}: {v.name},")
    L.append("  }")
    L.append("  let numeric_escapes : Map[String, NumericEscape] = {")
    for k, v in cls.NUMERIC_ESCAPES.items():
        L.append(
            f"    {mbt_str(k)}: {{ base: {v[0]}, min_digits: {v[1]}, max_digits: {v[2]}, max_value: {v[3]} }},"
        )
    L.append("  }")
    L.append("  let numeric_literals : Map[String, String] = {")
    for k, v in cls.NUMERIC_LITERALS.items():
        L.append(f"    {mbt_str(k)}: {mbt_str(v)},")
    L.append("  }")
    bse = cls.__dict__.get("BYTE_STRING_ESCAPES")
    L.append("  {")
    L.append("    single_tokens,")
    for attr in ["BIT_STRINGS", "BYTE_STRINGS", "HEX_STRINGS", "RAW_STRINGS", "HEREDOC_STRINGS", "UNICODE_STRINGS", "IDENTIFIERS", "QUOTES", "COMMENTS"]:
        L.append(f"    {attr.lower()}: {quote_specs(getattr(cls, attr))},")
    L.append(f"    string_escapes: [{', '.join(mbt_str(x) for x in cls.STRING_ESCAPES)}],")
    L.append("    byte_string_escapes: None,")
    L.append(f"    var_single_tokens: [{', '.join(mbt_char(x) for x in sorted(cls.VAR_SINGLE_TOKENS))}],")
    L.append(f"    escape_follow_chars: [{', '.join(mbt_str(x) for x in cls.ESCAPE_FOLLOW_CHARS)}],")
    L.append(f"    identifier_escapes: [{', '.join(mbt_str(x) for x in cls.IDENTIFIER_ESCAPES)}],")
    L.append(f"    heredoc_tag_is_identifier: {str(cls.HEREDOC_TAG_IS_IDENTIFIER).lower()},")
    L.append(f"    heredoc_string_alternative: {cls.HEREDOC_STRING_ALTERNATIVE.name},")
    L.append(f"    string_escapes_allowed_in_raw_strings: {str(cls.STRING_ESCAPES_ALLOWED_IN_RAW_STRINGS).lower()},")
    L.append("    numeric_escapes,")
    L.append(f"    drop_unknown_escapes: {str(cls.DROP_UNKNOWN_ESCAPES).lower()},")
    L.append(f"    nested_comments: {str(cls.NESTED_COMMENTS).lower()},")
    L.append(f"    hint_start: {mbt_str(cls.HINT_START)},")
    L.append(f"    tokens_preceding_hint: {tt_list(cls.TOKENS_PRECEDING_HINT)},")
    L.append("    keywords,")
    L.append(f"    commands: {tt_list(cls.COMMANDS)},")
    L.append(f"    command_prefix_tokens: {tt_list(cls.COMMAND_PREFIX_TOKENS)},")
    L.append("    numeric_literals,")
    L.append(f"    numbers_can_have_decimals: {str(cls.NUMBERS_CAN_HAVE_DECIMALS).lower()},")
    for d in ["quotes_map", "identifiers_map", "identifier_chars", "format_strings", "string_escapes_set", "byte_string_escapes_set", "escape_follow_chars_set", "identifier_escapes_set", "comments_map", "commands_set"]:
        L.append(f"    {d}: Map::new(),")
    L.append("    keyword_trie: Trie::new(),")
    L.append("  }")
    L.append("}")
    return L


def gen_base_tokenizer():
    from sqlglot.tokens import Tokenizer
    from sqlglot.jsonpath import JSONPathTokenizer
    L = ["// Code generated by tools/gen_meta.py. DO NOT EDIT.", ""]
    L += tokenizer_settings_full(Tokenizer, "base_tokenizer_settings_raw")
    L.append("")
    L += tokenizer_settings_full(JSONPathTokenizer, "base_jsonpath_tokenizer_settings_raw")
    with open(os.path.join(OUT, "gen_tokenizer.mbt"), "w") as f:
        f.write("\n".join(L) + "\n")


if __name__ == "__main__":
    gen_base_tokenizer()


def gen_function_by_name():
    L = ["// Code generated by tools/gen_meta.py. DO NOT EDIT.", ""]
    L.append("///|")
    L.append("/// `exp.FUNCTION_BY_NAME`: SQL function names to function kinds.")
    L.append("pub let function_by_name : Array[(String, Kind)] = [")
    for name, cls in exp.FUNCTION_BY_NAME.items():
        L.append(f"  ({mbt_str(name)}, {kind_name(cls.__name__)}),")
    L.append("]")
    with open(os.path.join(OUT, "gen_functions.mbt"), "w") as f:
        f.write("\n".join(L) + "\n")


if __name__ == "__main__":
    gen_function_by_name()
