"""Optimizer stress fixtures over the dialect test corpus.

Takes the JSON lines produced by tools/extract_dialect_tests.py, keeps the distinct
(read dialect, sql) pairs that parse to a query, and records Python's
`optimize(parse_one(sql, read), dialect=read).sql(read)` (or the error type).

    python tools/gen_optimizer_dialect_stress.py cases.jsonl [max_per_dialect]
"""

import json
import os
import sys
import warnings

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SG = os.path.join(ROOT, ".repos", "sqlglot")
sys.path.insert(0, SG)
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
try:
    import dateutil.relativedelta  # noqa: F401
except ImportError:
    sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), "pyshim"))
warnings.filterwarnings("ignore")

import logging  # noqa: E402

logging.getLogger("sqlglot").setLevel(logging.CRITICAL)

from gen_meta import mbt_str  # noqa: E402

from sqlglot import exp, parse_one  # noqa: E402
from sqlglot.optimizer import optimize  # noqa: E402

OUT = os.path.join(ROOT, "src", "optimizer_tests")


def main():
    path = sys.argv[1]
    max_per = int(sys.argv[2]) if len(sys.argv) > 2 else 200
    seen = set()
    per_dialect = {}
    records = []
    for line in open(path):
        case = json.loads(line)
        read = case.get("read") or ""
        sql = case["sql"]
        key = (read, sql)
        if key in seen:
            continue
        seen.add(key)
        if per_dialect.get(read, 0) >= max_per:
            continue
        try:
            expression = parse_one(sql, read=read)
        except Exception:  # noqa: BLE001
            continue
        if not isinstance(expression, exp.Query):
            continue
        per_dialect[read] = per_dialect.get(read, 0) + 1
        try:
            out = optimize(expression, dialect=read).sql(dialect=read)
        except Exception as e:  # noqa: BLE001
            out = f"ERROR: {type(e).__name__}: {e}"
        records.append((read, sql, out))

    with open(os.path.join(OUT, "fixture_dialect_stress_test.mbt"), "w") as f:
        f.write("// Code generated by tools/gen_optimizer_dialect_stress.py. DO NOT EDIT.\n\n")
        f.write("///|\nlet dialect_stress_fixtures : Array[String] = [\n")
        for read, sql, out in records:
            f.write(f"  {mbt_str(read)}, {mbt_str(sql)}, {mbt_str(out)},\n")
        f.write("]\n")
    print("cases:", len(records), per_dialect)


if __name__ == "__main__":
    main()
