"""Generate MoonBit test fixtures from the Python sqlglot test suite."""

import json
import os
import sys
import warnings

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SG = os.path.join(ROOT, ".repos", "sqlglot")
sys.path.insert(0, SG)
warnings.filterwarnings("ignore")

from gen_meta import mbt_str  # noqa: E402

OUT = os.path.join(ROOT, "src", "tests")


def write_lines_const(f, name, lines):
    f.write("///|\n")
    f.write(f"let {name} : Array[String] = [\n")
    for line in lines:
        f.write(f"  {mbt_str(line)},\n")
    f.write("]\n\n")


def gen_token_fixtures():
    from sqlglot.tokens import Tokenizer

    lines = []
    for line in open(os.path.join(SG, "tests/fixtures/identity.sql")):
        line = line.rstrip("\n")
        if not line.strip():
            continue
        try:
            toks = Tokenizer().tokenize(line)
        except Exception:
            continue
        digest = " ".join(
            f"{t.token_type.name}:{t.text}@{t.line},{t.col},{t.start},{t.end}"
            + (f"#{len(t.comments)}" if t.comments else "")
            for t in toks
        )
        lines.append(line)
        lines.append(digest)
    with open(os.path.join(OUT, "fixture_tokens_test.mbt"), "w") as f:
        f.write("// Code generated by tools/gen_fixtures.py. DO NOT EDIT.\n\n")
        write_lines_const(f, "token_fixtures", lines)


if __name__ == "__main__":
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    gen_token_fixtures()


def canonical(node):
    """Canonical AST dump shared with MoonBit's Expr::canonical()."""
    import json
    from sqlglot import exp
    from sqlglot.expressions import DType

    def val(v):
        if isinstance(v, exp.Expr):
            return canonical(v)
        if isinstance(v, list):
            return "[" + ",".join(val(x) for x in v if x is not None) + "]"
        if isinstance(v, bool):
            return "true" if v else "false"
        if isinstance(v, DType):
            return "DType." + v.name
        if isinstance(v, int):
            return str(v)
        if isinstance(v, str):
            return json.dumps(v, ensure_ascii=False)
        return json.dumps(str(v), ensure_ascii=False)

    order = list(type(node).arg_types)
    keys = [k for k in order if k in node.args] + sorted(k for k in node.args if k not in order)
    parts = []
    for k in keys:
        v = node.args[k]
        if v is None or (isinstance(v, list) and not v):
            continue
        parts.append(f"{k}={val(v)}")
    if node.comments:
        parts.append("#c=" + json.dumps(node.comments, ensure_ascii=False))
    return f"{type(node).__name__}({','.join(parts)})"


def gen_ast_fixtures():
    import sqlglot

    import glob

    lines = []
    seen = set()

    def add(sql):
        if sql in seen or not sql.strip():
            return
        seen.add(sql)
        try:
            e = sqlglot.parse_one(sql)
        except Exception:
            return
        if e is None:
            return
        lines.append(sql)
        lines.append(canonical(e))

    for line in open(os.path.join(SG, "tests/fixtures/identity.sql")):
        add(line.rstrip("\n"))
    # pretty.sql and optimizer fixtures: statements separated by ';' at end of line
    files = [os.path.join(SG, "tests/fixtures/pretty.sql")] + sorted(
        glob.glob(os.path.join(SG, "tests/fixtures/optimizer/*.sql"))
    )
    for path in files:
        buf = []
        for line in open(path):
            line = line.rstrip("\n")
            if line.startswith("#") or line.startswith("--"):
                continue
            if not line.strip():
                if buf:
                    add("\n".join(buf).rstrip(";"))
                buf = []
                continue
            buf.append(line)
            if line.endswith(";"):
                add("\n".join(buf).rstrip(";"))
                buf = []
        if buf:
            add("\n".join(buf).rstrip(";"))
    with open(os.path.join(OUT, "fixture_ast_test.mbt"), "w") as f:
        f.write("// Code generated by tools/gen_fixtures.py. DO NOT EDIT.\n\n")
        write_lines_const(f, "ast_fixtures", lines)


if __name__ == "__main__":
    gen_ast_fixtures()
