"""Generate MoonBit lineage fixtures by recording the lineage() calls of tests/test_lineage.py.

Every call made by the Python test-suite whose arguments can be expressed as data
(strings, dicts of strings) is replayed and its graph is dumped canonically (children
sorted, so that Python's set iteration order doesn't matter).

Run with the scratchpad venv python:
    python tools/gen_lineage_fixtures.py
"""

import json
import os
import sys
import unittest
import warnings

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SG = os.path.join(ROOT, ".repos", "sqlglot")
sys.path.insert(0, SG)
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
warnings.filterwarnings("ignore")

import logging  # noqa: E402

logging.getLogger("sqlglot").setLevel(logging.CRITICAL)

from gen_meta import mbt_str  # noqa: E402

import sqlglot  # noqa: E402
import sqlglot.lineage as lineage_mod  # noqa: E402
from sqlglot import exp  # noqa: E402
from sqlglot.schema import MappingSchema  # noqa: E402

OUT = os.path.join(ROOT, "src", "lineage_tests")

real_lineage = lineage_mod.lineage
recorded = []


def dump(node, dialect, depth=0, seen=None):
    seen = set() if seen is None else seen
    def sql(e):
        try:
            return e.sql(dialect=dialect)
        except Exception as ex:  # noqa: BLE001
            return f"<{type(ex).__name__}>"

    head = f"{node.name} | {node.source_name} | {node.reference_node_name} | {sql(node.expression)} | {sql(node.source)}"
    if id(node) in seen or depth > 30:
        return head + " ..."
    seen = seen | {id(node)}
    children = sorted(dump(d, dialect, depth + 1, seen) for d in node.downstream)
    if not children:
        return head
    inner = "\n".join("  " + line for c in children for line in c.split("\n"))
    return head + "\n" + inner


def recording_lineage(column, sql, schema=None, sources=None, dialect=None, **kwargs):
    result = real_lineage(column, sql, schema=schema, sources=sources, dialect=dialect, **kwargs)
    try:
        rec = encode_call(column, sql, schema, sources, dialect, kwargs)
    except Exception:  # noqa: BLE001
        rec = None
    if rec is not None:
        # dump now: later test code (e.g. to_html) mutates the graph's expressions
        if isinstance(result, dict):
            out = "\n".join(f"[{name}]\n" + dump(n, dialect) for name, n in result.items())
        else:
            out = dump(result, dialect)
        recorded.append((rec, out))
    return result


def encode_call(column, sql, schema, sources, dialect, kwargs):
    if kwargs.keys() - {"trim_selects"}:
        return None
    if not (column is None or isinstance(column, str)):
        return None
    if isinstance(sql, exp.Expr):
        sql = sql.sql(dialect=dialect)
    if isinstance(schema, MappingSchema):
        return None
    if sources:
        srcs = {}
        for k, v in sources.items():
            srcs[k] = v.sql(dialect=dialect) if isinstance(v, exp.Expr) else v
        sources = srcs

    def enc_schema(s):
        if isinstance(s, dict):
            return {k: enc_schema(v) for k, v in s.items()}
        if isinstance(s, exp.DataType):
            raise ValueError
        return s

    return {
        "column": column,
        "sql": sql,
        "schema": enc_schema(schema) if schema else None,
        "sources": sources or None,
        "dialect": dialect or "",
        "trim_selects": kwargs.get("trim_selects", True),
    }


def main():
    lineage_mod.lineage = recording_lineage
    import tests.test_lineage as tl

    tl.lineage = recording_lineage
    sqlglot.schema = MappingSchema()
    suite = unittest.defaultTestLoader.loadTestsFromModule(tl)
    unittest.TextTestRunner(stream=open(os.devnull, "w")).run(suite)

    records = []
    seen = set()
    for rec, out in recorded:
        key = json.dumps(rec)
        if key in seen:
            continue
        seen.add(key)
        records.append((key, out))

    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, "fixture_lineage_test.mbt"), "w") as f:
        f.write("// Code generated by tools/gen_lineage_fixtures.py. DO NOT EDIT.\n\n")
        f.write("///|\nlet lineage_fixtures : Array[String] = [\n")
        for key, out in records:
            f.write(f"  {mbt_str(key)},\n  {mbt_str(out)},\n")
        f.write("]\n")
    print("lineage calls:", len(records))


if __name__ == "__main__":
    main()
