"""Generate MoonBit test fixtures from the Python sqlglot test suite."""

import json
import os
import sys
import warnings

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SG = os.path.join(ROOT, ".repos", "sqlglot")
sys.path.insert(0, SG)
warnings.filterwarnings("ignore")

from gen_meta import mbt_str  # noqa: E402

OUT = os.path.join(ROOT, "src", "tests")


def write_lines_const(f, name, lines):
    f.write("///|\n")
    f.write(f"let {name} : Array[String] = [\n")
    for line in lines:
        f.write(f"  {mbt_str(line)},\n")
    f.write("]\n\n")


def gen_token_fixtures():
    from sqlglot.tokens import Tokenizer

    lines = []
    for line in open(os.path.join(SG, "tests/fixtures/identity.sql")):
        line = line.rstrip("\n")
        if not line.strip():
            continue
        try:
            toks = Tokenizer().tokenize(line)
        except Exception:
            continue
        digest = " ".join(
            f"{t.token_type.name}:{t.text}@{t.line},{t.col},{t.start},{t.end}"
            + (f"#{len(t.comments)}" if t.comments else "")
            for t in toks
        )
        lines.append(line)
        lines.append(digest)
    with open(os.path.join(OUT, "fixture_tokens_test.mbt"), "w") as f:
        f.write("// Code generated by tools/gen_fixtures.py. DO NOT EDIT.\n\n")
        write_lines_const(f, "token_fixtures", lines)


if __name__ == "__main__":
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    gen_token_fixtures()
